config/routes.rb
Tuteable::Application.routes.draw do
  devise_for :admins

  resources :requests do
    resources :chats do
      resources :messages
    end
  end

  root :to => "requests#index"

  
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin)
    admin ||= Admin.new

    if admin.role == "tutor"
      can :manage, :all
    else
      can :read, :all
      can :create, Request
      can :update, Request
      can :create, Message
      can :update, Message
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  ROLES = %w[tutor user]


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  attr_accessible :category, :content, :offer, :request_id, :sessiontime, :subcategor, :subject, :tutor_id, :user_id, :viewed

  belongs_to :request
  has_many :messages
  belongs_to :user
  belongs_to :tutor
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :chat
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :id, :category, :description, :sessiontime, :subcategory, :subject, :urgency_id, :lastping, :tutor_id, :user_id, :paid, :price, :created_at, :updated_at, :title

  has_many :chats
  belongs_to :user
  belongs_to :tutor
end

app/models/requests.rb
class Requests < ActiveRecord::Base
  attr_accessible :id, :category, :description, :sessiontime, :subcategory, :subject, :urgency_id, :lastping, :tutor_id, :user_id, :paid, :price, :created_at, :updated_at
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :requests
  has_many :chats
end

app/models/tutors.rb
class Tutors < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :requests
  has_many :chats
end

app/models/users.rb
class Users < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  alias_method :current_user, :current_admin

  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :get_request
  load_and_authorize_resource

  def index
    #@chats = Chat.all
    @chats = @request.chats
  end

  def show
    #@chat = Chat.find(params[:id])
    @chat = @request.chats.find(params[:id])

    @message = @chat.messages.build
  end

  def new
    #@chat = Chat.new
    @request = Request.find(params[:request_id])
    @chat = @request.chats.build
  end

  def edit
    #@chat = Chat.find(params[:id])
    @chat = @request.chats.find(params[:id])
  end

  def create
    #@chat = Chat.new(params[:request])
    @chat = @request.chats.build(params[:chat])

    if @chat.save
      #redirect_to request_chats_url(@request)
      redirect_to @request
    else
      render action: "new"
    end
  end

  def update
    #@chat = Chat.find(params[:id])
    @chat = @request.chats.find(params[:id])

    if @chat.update_attributes(params[:chat])
      #redirect_to request_chats_url(@request)
      redirect_to @request
    else
      render action: "edit"
    end
  end

  private
  def get_request
    @request = Request.find(params[:request_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :get_chat
  load_and_authorize_resource

  def index
    #@messages = Message.all
    @messages = @chat.messages
  end

  def show
    #@message = Message.find(params[:id])
    @message = @chat.messages.find(params[:id])
  end

  def new
    #@message = Message.new
    @chat = Chat.find(params[:chat_id])
    @message = @chat.messages.build
  end

  def edit
    #@message = Message.find(params[:id])
    @message = @chat.messages.find(params[:id])
  end

  def create
    #@message = Message.new(params[:message])
    @message = @chat.messages.build(params[:message])

    if @message.save
      #redirect_to request_chats_url(@request)
      redirect_to [@request, @chat]
    else
      render action: "new"
    end
  end

  def update
    #@message = Message.find(params[:id])
    @message = @chat.messages.find(params[:id])

    if @message.update_attributes(params[:message])
      #redirect_to request_chats_url(@request)
      redirect_to [@request, @chat]
    else
      render action: "edit"
    end
  end

  private
  def get_chat
    @request = Request.find(params[:request_id])
    @chat = @request.chats.find(params[:chat_id])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate_admin!
  load_and_authorize_resource

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])

    #@chats = Chat.order :id
  end

  def new
    @request = Request.new
  end

  def edit
    @request = Request.find(params[:id])
  end

  def create
    @request = Request.new(params[:request])

    if @request.save
      redirect_to @request
    else
      render action: "new"
    end
  end

  def update
    @request = Request.find(params[:id])

    if @request.update_attributes(params[:request])
      redirect_to @request
    else
      render action: "edit"
    end
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def action_title(title)
    content_for :title, title
    #content_tag :h1, title
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/chats/_form.html.erb
<%= form_for([@request, @chat]) do |f| %>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
    <%= f.hidden_field :user_id, :value => current_admin.id %>
  <p>
    <%= f.submit "Send" %>
  </p>
<% end %>

app/views/chats/edit.html.erb
<%= action_title "Edit chat" %>

<%= render 'form' %>

<%= link_to 'Show', [@request, @chat] %>
<%= link_to 'Back', request_chats_path(@request) %>

app/views/chats/index.html.erb
<%= action_title "Chats" %>

<%= link_to "New Chat", new_request_chat_path(@request) %>

<ul>
  <% @request.chats.each do |chat| %>
    <li><%= chat.content %></li>
  <% end %>
</ul>

app/views/chats/new.html.erb
<%= action_title "Create new chat" %>

<%= render 'form' %>

<%= link_to 'Back', @request %>

app/views/chats/show.html.erb
<%= action_title "Chat" %>

<div class="show-single-request ">
  <%= link_to "Edit", edit_request_chat_path(@request, @chat) %><br>
  <%= link_to "Back", request_chats_path(@request) %><br><br>

  <div class="row">
    <div class="col-md-2">
      <div class="user-img"><br> User Image
      </div>
    </div>
    <div class="col-md-10">
      <p id="description" class="single-message"><b>Sent <%= time_ago_in_words(@chat.created_at) %> days ago:</b> <%= @chat.content %></p>
    </div>
  </div>

  <br>

  <% @chat.messages.each do |message| %>
  <div class="row">
    <div class="col-md-2">
      <div class="user-img"><br> User Image
      </div>
    </div>
    <div class="col-md-10">
      <p class="single-message"><b>Sent <%= time_ago_in_words(@chat.created_at) %> days ago:</b> <%= message.content %></p>
    </div>
  </div>
  <br>
  <% end %>

  <div class="row">
  <br>
    <div class="col-md-2">
    </div>
    <div class="col-md-10">
      <%= form_for([@request, @chat, @message]) do |f| %>
        <div class="field">
          <%= f.text_area :content, placeholder: 'Your message' %>
        </div>
          <%= f.hidden_field :user_id, :value => current_admin.id %>
        <div class="actions">
          <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>
            <div class="col-md-4"><%= f.submit "SEND" %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuteable :: <%= content_for :title%></title>
  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row top-bar">
    <div class="col-md-4 top-bar-col top-bar-1"></div>
    <div class="col-md-4 top-bar-col top-bar-2"></div>
    <div class="col-md-4 top-bar-col top-bar-3"></div>
  </div>

  <div class="container">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="header">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-user"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <p class="navbar-text pull-right">
                <% if admin_signed_in? %>
                  Logged in as <strong><%= current_admin.email %></strong>.
                  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                  <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
                <% end %>
              </p>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-envelope"></span>
          </a>
        </li>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-asterisk"></span>
          </a>
        </li>
      </ul>
      <h3 class="text-muted">Tute<span class="header-h3-tuteable-2">able</span></h3>
    </div>

    <div class="requests-container">
      <div class="requests-container-header">
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle requests-link" data-toggle="dropdown">
            Request
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Requests", requests_path, class: "requests-link" %></li>
            <li><%= link_to "New Request", new_request_path, class: "requests-link" %></li>
          </ul>
        </div>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle requests-link" data-toggle="dropdown">
            Scheduled
          </button>
        </div>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle requests-link" data-toggle="dropdown">
            History
          </button>
        </div>
        <input type="text" >
      </div>

      <%= yield %>
    </div>

  </div>

  <div class="social-icons">
    <div class="container">
      <div class="row">
        <div class="col-md-2 col-md-offset-1">
          <%= image_tag("facebook.png") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("twitter.png") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("dropbox.png") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("linkedin.png") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("gplus.png") %>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-menu">
    <div class="container">
      <div class="row">
        <div class="col-md-2">About Us</div>
        <div class="col-md-2">How It Works</div>
        <div class="col-md-2">Contact</div>
        <div class="col-md-2">Privacy</div>
        <div class="col-md-2">Terms</div>
        <div class="col-md-2">Support</div>
      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <p class="footer-bottom-title">Tuteable</p>
    <p class="footer-bottom-copyright">COPYRIGHT @ 2014 TUTEABLE. ALL RIGHTS RESERVED</p>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.content %></td>
    <td><%= message.user_id %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
    <%= f.hidden_field :user_id, :value => current_admin.id %>
  <p>
    <%= f.submit "Send" %>
  </p>
<% end %>

app/views/requests/edit.html.erb
<%= action_title "Edit request" %>

<%= render 'form' %>

<%= link_to 'Show', @request %>
<%= link_to 'Back', request_path %>

app/views/requests/index.html.erb
<%= action_title "Requests" %>

<% @requests.each do |request| %>
  <div class="single-request">
    <div class="row">
      <div class="col-md-2">
        <div class="user-img"></div>
      </div>
      <div class="col-md-10">
        <h3 class="request-title">*<%= request.title %>* - <span style="font-weight:normal;font-style:italic;font-size:17px">Exp 20/01/13</span></h3>
        <p class="user-request-creator"><b><% @request_user_name = Admin.find(request.user_id) %><%= @request_user_name[:email] %> | </b> Web Designer</p>
        <%= link_to "MESSAGES", request, class: "messages-button" %>
        <%= link_to "RESPOND", request, class: "respond-button" %>
        <div class="row">
          <div class="col-md-3"><p class="request-date"><%= time_ago_in_words(request.created_at) %></p></div>
          <div class="col-md-3"><p class="request-date"><%= request.created_at.strftime("%l:%M %p | %d/%m/%y") %></p></div>
          <div class="col-md-3"><p class="request-date">$ <%= request.price %></p></div>
          <div class="col-md-3"></div>
        </div>
        <p><b><%= request.description %></b></p>
        <div class="row">
          <div class="col-md-8">
            <p><span class="glyphicon glyphicon-envelope"></span> <b>Sent <%= time_ago_in_words(Chat.where(request_id: request.id).last.created_at) %> ago:</b> <%= Chat.where(request_id: request.id).last.content %></p>
          </div>
          <div class="col-md-4">
            <p><%= link_to "view message history", request %></p>
          </div>
        </div>

        <!--
        <div class="container">
          <p>Number of chats: <%= request.chats.count %></p>
        </div>
        -->
      </div>
    </div>
  </div>
<% end %>

<div class="single-request">
  <div class="row chats-request-page">
    <div class="col-md-2">
    </div>
    <div class="col-md-10 chats-container">
      <div class="chats-list">
      <% @chat_request_page = Chat.find(1) %>
      <% Chat.find(1).messages.each do |message| %>
      <div class="row">
        <div class="col-md-2">
          <div class="user-img"></div>
        </div>
        <div class="col-md-10">
          <p class="single-message"><b>Sent <%= time_ago_in_words(@chat_request_page.created_at) %> days ago:</b> <%= message.content %></p>
        </div>
      </div>
      <br>
      <% end %>
      </div>
      <div>
        <form>
          <input class="message-input" type="text" placeholder="Your message">
          <br>
          <div class="row">
            <div class="col-md-4">
              <input type="text" placeholder="Change bid">
            </div>
            <div class="col-md-4">
              <input type="text" placeholder="Change time">
            </div>
            <div class="col-md-4">
              <input type="submit" value="SEND">
            </div>
          </div>
        </form>
        <div class="row">
          <div class="col-md-8">
          </div>
          <div class="col-md-4">
            <p><%= link_to "view message history" %></p>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/requests/new.html.erb
<%= action_title "Create new request" %>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<%= action_title "Request" %>

<div class="single-request">
  <div class="row">
    <div class="col-md-2">
      <div class="user-img"><br> User Image
      </div>
    </div>
    <div class="col-md-10">
      <h3 id="title" class="request-title">*<%= @request.title %>*</h3>
      <p class="user-request-creator"><% @request_user_name = Admin.find(@request.user_id) %><%= @request_user_name[:email] %></p>
      <div class="row">
        <div class="col-md-3"><p class="request-date"><%= time_ago_in_words(@request.created_at) %></p></div>
        <div class="col-md-3"><p class="request-date"><%= @request.created_at.strftime("%l:%M %p | %d/%m/%y") %></p></div>
        <div class="col-md-3"><p class="request-date">$ <%= @request.price %></p></div>
        <div class="col-md-3"></div>
      </div>
      <p><b><%= @request.description %></b></p>
      <div class="row">
        <div class="col-md-8">
          <p><b>Sent <%= time_ago_in_words(Chat.where(request_id: @request.id).last.created_at) %> ago:</b> <%= Chat.where(request_id: @request.id).last.content %></p>
        </div>
        <div class="col-md-4">
          <p><%= link_to "view message history", @request %></p>
        </div>
      </div>

      <p><%= link_to "Edit Request", edit_request_path(@request) %></p>
      <p><%= link_to "Back", requests_path %></p><br>

      <div class="show-single-request">
        <h4>Chats
          <% if current_admin.role == "tutor" %>
            <%= link_to "New Chat", new_request_chat_path(@request), class: "new-request-button" %>
          <% end %>
        </h4>
        <% for chat in @request.chats %>
          <%= link_to([@request, chat], :class => "single-chat") do %>
            <p>Tutor: <% @chat_user_name = Admin.find(chat.user_id) %><%= @chat_user_name[:email] %></p>
            <p>Number of messages: <%= chat.messages.count %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>